In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../satelliteData/satRgbFinal4.csv")

In [3]:
ref_point_keys = []
lats = []
lons = []
for label in df.sat_label:
    temp = df.loc[df.sat_label == label]
    lat_NW = temp['sat_Lat-NW'].values[0]
    lon_NW = temp['sat_Lon-NW'].values[0] 
    lat_SE = temp['sat_Lat-SE'].values[0]
    lon_SE = temp['sat_Lon-SE'].values[0] 
    lat_center = temp['sat_Lat-Center'].values[0]
    lon_center = temp['sat_Lon-Center'].values[0]
    for i in range(1, 4):
        new_label = label + '_' + str(i)
        ref_point_keys.append(new_label)
        lats.append(lat_NW)
        if i == 1:
            lons.append(lon_NW)
        elif i == 2:
            lons.append(lon_center)
        else:
            lons.append(lon_SE)
    for i in range(4, 7):
        new_label = label + '_' + str(i)
        ref_point_keys.append(new_label)
        lats.append(lat_center)
        if i == 4:
            lons.append(lon_NW)
        elif i == 5:
            lons.append(lon_center)
        else:
            lons.append(lon_SE)
    for i in range(7, 10):
        new_label = label + '_' + str(i)
        ref_point_keys.append(new_label)
        lats.append(lat_SE)
        if i == 7:
            lons.append(lon_NW)
        elif i == 8:
            lons.append(lon_center)
        else:
            lons.append(lon_SE)

In [4]:
ref_lat_lons = pd.DataFrame(data = {'land_ref_label': ref_point_keys, 'land_Lat-Center': lats, 'land_Lon-Center': lons})
ref_lat_lons

     land_ref_label  land_Lat-Center  land_Lon-Center
0      farmCherry_1        40.332624       -74.749758
1      farmCherry_2        40.332624       -74.728754
2      farmCherry_3        40.332624       -74.707701
3      farmCherry_4        40.322965       -74.749758
4      farmCherry_5        40.322965       -74.728754
..              ...              ...              ...
166  urbanLibrary_5        40.351510       -74.660325
167  urbanLibrary_6        40.351510       -74.648996
168  urbanLibrary_7        40.346620       -74.671573
169  urbanLibrary_8        40.346620       -74.660325
170  urbanLibrary_9        40.346620       -74.648996

[171 rows x 3 columns]

Add empty region columns

In [5]:
ref_lat_lons[['GRASSY', 'DENSE_WOOD', 'WOODY', 'SUBURBAN', 'WATERY', 'URBAN', 'AGRICULTURAL']] = 0
ref_lat_lons

,land_ref_label,land_Lat-Center,land_Lon-Center,GRASSY,DENSE_WOOD,WOODY,SUBURBAN,WATERY,URBAN,AGRICULTURAL
0,farmCherry_1,40.332624,-74.749758,0,0,0,0,0,0,0
1,farmCherry_2,40.332624,-74.728754,0,0,0,0,0,0,0
2,farmCherry_3,40.332624,-74.707701,0,0,0,0,0,0,0
3,farmCherry_4,40.322965,-74.749758,0,0,0,0,0,0,0
4,farmCherry_5,40.322965,-74.728754,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
166,urbanLibrary_5,40.351510,-74.660325,0,0,0,0,0,0,0
167,urbanLibrary_6,40.351510,-74.648996,0,0,0,0,0,0,0
168,urbanLibrary_7,40.346620,-74.671573,0,0,0,0,0,0,0
169,urbanLibrary_8,40.346620,-74.660325,0,0,0,0,0,0,0
170,urbanLibrary_9,40.346620,-74.648996,0,0,0,0,0,0,0

Let's save this to CSV for collecting the landcover percentages.

In [6]:
ref_lat_lons.tail(9).to_csv("broad_landcover.csv", index = False)

## Stitching together results

We'll pull in the main landcover file (`landcover-nj-2023.csv`) which already has local values to add in the broad values.

In [7]:
df2 = pd.read_csv("../satelliteData/landcover-nj-2023.csv")
df2.head()

,land_ref_label,land_Lat-Center,land_Lon-Center,land_Lat-NW,land_Lon-NW,land_Lat-SE,land_Lon-SE,GRASSY_LOCAL,DENSE_WOOD_LOCAL,WOODY_LOCAL,...,WATERY_LOCAL,URBAN_LOCAL,AGRICULTURAL_LOCAL,GRASSY_BROAD,DENSE_WOOD_BROAD,WOODY_BROAD,SUBURBAN_BROAD,WATERY_BROAD,URBAN_BROAD,AGRICULTURAL_BROAD
0,farmCherry_1,40.332624,-74.749758,40.336247,-74.754337,40.329001,-74.745179,0.029125,0.257376,0.410786,...,0.265962,0.011070,0.000000,0,0,0,0,0,0,0
1,farmCherry_2,40.332624,-74.728754,40.336247,-74.733333,40.329001,-74.724175,0.211565,0.089366,0.027461,...,0.191876,0.121909,0.281510,0,0,0,0,0,0,0
2,farmCherry_3,40.332624,-74.707701,40.336247,-74.712280,40.329001,-74.703122,0.214380,0.243008,0.121227,...,0.320442,0.002664,0.000000,0,0,0,0,0,0,0
3,farmCherry_4,40.322965,-74.749758,40.326588,-74.754337,40.319342,-74.745179,0.460249,0.269608,0.087560,...,0.163003,0.010175,0.000037,0,0,0,0,0,0,0
4,farmCherry_5,40.322965,-74.728754,40.326588,-74.733333,40.319342,-74.724175,0.434925,0.077210,0.216792,...,0.161405,0.000995,0.014261,0,0,0,0,0,0,0

In [15]:
df2.tail()

,land_ref_label,land_Lat-Center,land_Lon-Center,land_Lat-NW,land_Lon-NW,land_Lat-SE,land_Lon-SE,GRASSY_LOCAL,DENSE_WOOD_LOCAL,WOODY_LOCAL,...,WATERY_LOCAL,URBAN_LOCAL,AGRICULTURAL_LOCAL,GRASSY_BROAD,DENSE_WOOD_BROAD,WOODY_BROAD,SUBURBAN_BROAD,WATERY_BROAD,URBAN_BROAD,AGRICULTURAL_BROAD
166,urbanLibrary_5,40.35151,-74.660325,40.355133,-74.664904,40.347887,-74.655746,0.099046,0.000000,0.000000,...,0.000000,0.834969,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,urbanLibrary_6,40.35151,-74.648996,40.355133,-74.653575,40.347887,-74.644417,0.031157,0.008836,0.000000,...,0.000000,0.485591,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,urbanLibrary_7,40.34662,-74.671573,40.350243,-74.676152,40.342997,-74.666994,0.000989,0.018350,0.020010,...,0.000000,0.132312,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,urbanLibrary_8,40.34662,-74.660325,40.350243,-74.664904,40.342997,-74.655746,0.002751,0.000000,0.008109,...,0.000000,0.942315,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,urbanLibrary_9,40.34662,-74.648996,40.350243,-74.653575,40.342997,-74.644417,0.222315,0.064744,0.006634,...,0.009602,0.571475,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Read in majority of broad landcover data (missing Urban Library).

In [9]:
broad_regions = pd.read_csv("broad_landcover_complete.csv")
broad_regions

,ref_label,lat,lon,GRASSY,DENSE_WOOD,WOODY,SUBURBAN,WATERY,URBAN,AGRICULTURAL
0,farmCherry_1,40.332624,-74.749758,0.163110,0.204270,0.299284,0.077095,0.237492,0.010225,0.008525
1,farmCherry_2,40.332624,-74.728754,0.217497,0.148580,0.030378,0.137914,0.291489,0.081683,0.092459
2,farmCherry_3,40.332624,-74.707701,0.190709,0.246658,0.050040,0.291402,0.178362,0.042830,0.000000
3,farmCherry_4,40.322965,-74.749758,0.431917,0.180800,0.137774,0.034875,0.200815,0.006344,0.007476
4,farmCherry_5,40.322965,-74.728754,0.318546,0.119464,0.074341,0.158355,0.270207,0.019533,0.039555
...,...,...,...,...,...,...,...,...,...,...
157,univSolarFarm_5,40.334348,-74.647146,0.316755,0.121906,0.059572,0.064294,0.175478,0.258962,0.003032
158,univSolarFarm_6,40.334348,-74.626075,0.206241,0.023644,0.039318,0.061023,0.236169,0.404179,0.029427
159,univSolarFarm_7,40.325165,-74.668232,0.230172,0.414365,0.001463,0.006730,0.233760,0.113511,0.000000
160,univSolarFarm_8,40.325165,-74.647146,0.155794,0.036963,0.074391,0.063620,0.120003,0.546198,0.003032
161,univSolarFarm_9,40.325165,-74.626075,0.057474,0.104632,0.032882,0.183739,0.263820,0.272370,0.085083

Get the urban library broad data too.

In [10]:
broad_lib = pd.read_csv("broad_landcover_library_complete.csv")

In [11]:
broad_lib.head()

,ref_label,lat,lon,GRASSY,DENSE_WOOD,WOODY,SUBURBAN,WATERY,URBAN,AGRICULTURAL
0,urbanLibrary_1,40.357259,-74.671573,0.125826,0.162260,0.005548,0.366643,0.105553,0.178549,0.055621
1,urbanLibrary_2,40.357259,-74.660325,0.132020,0.022914,0.000000,0.373323,0.024619,0.430181,0.016942
2,urbanLibrary_3,40.357259,-74.648996,0.048423,0.006504,0.000000,0.618944,0.002702,0.323427,0.000000
3,urbanLibrary_4,40.351510,-74.671573,0.038103,0.061693,0.008801,0.568359,0.039955,0.283089,0.000000
4,urbanLibrary_5,40.351510,-74.660325,0.065830,0.001245,0.002052,0.215779,0.009800,0.705294,0.000000

Add the first chunk, then we'll add the library data.

In [12]:
for ref_label in df2.land_ref_label[:162]:
    temp = broad_regions.loc[broad_regions.ref_label == ref_label]
    df2.loc[df2.land_ref_label == ref_label, 'GRASSY_BROAD'] = temp.GRASSY
    df2.loc[df2.land_ref_label == ref_label, 'DENSE_WOOD_BROAD'] = temp.DENSE_WOOD
    df2.loc[df2.land_ref_label == ref_label, 'WOODY_BROAD'] = temp.WOODY
    df2.loc[df2.land_ref_label == ref_label, 'SUBURBAN_BROAD'] = temp.SUBURBAN
    df2.loc[df2.land_ref_label == ref_label, 'WATERY_BROAD'] = temp.WATERY
    df2.loc[df2.land_ref_label == ref_label, 'URBAN_BROAD'] = temp.URBAN
    df2.loc[df2.land_ref_label == ref_label, 'AGRICULTURAL_BROAD'] = temp.AGRICULTURAL

In [21]:
for ref_label in df2.land_ref_label[162:]:
    temp = broad_lib.loc[broad_lib.ref_label == ref_label]
    df2.loc[df2.land_ref_label == ref_label, 'GRASSY_BROAD'] = temp.GRASSY.values[0]
    df2.loc[df2.land_ref_label == ref_label, 'DENSE_WOOD_BROAD'] = temp.DENSE_WOOD.values[0]
    df2.loc[df2.land_ref_label == ref_label, 'WOODY_BROAD'] = temp.WOODY.values[0]
    df2.loc[df2.land_ref_label == ref_label, 'SUBURBAN_BROAD'] = temp.SUBURBAN.values[0]
    df2.loc[df2.land_ref_label == ref_label, 'WATERY_BROAD'] = temp.WATERY.values[0]
    df2.loc[df2.land_ref_label == ref_label, 'URBAN_BROAD'] = temp.URBAN.values[0]
    df2.loc[df2.land_ref_label == ref_label, 'AGRICULTURAL_BROAD'] = temp.AGRICULTURAL.values[0]

In [22]:
df2.tail(9)

,land_ref_label,land_Lat-Center,land_Lon-Center,land_Lat-NW,land_Lon-NW,land_Lat-SE,land_Lon-SE,GRASSY_LOCAL,DENSE_WOOD_LOCAL,WOODY_LOCAL,...,WATERY_LOCAL,URBAN_LOCAL,AGRICULTURAL_LOCAL,GRASSY_BROAD,DENSE_WOOD_BROAD,WOODY_BROAD,SUBURBAN_BROAD,WATERY_BROAD,URBAN_BROAD,AGRICULTURAL_BROAD
162,urbanLibrary_1,40.357259,-74.671573,40.360882,-74.676152,40.353636,-74.666994,0.098336,0.146085,0.010292,...,0.178456,0.084551,0.074067,0.125826,0.162260,0.005548,0.366643,0.105553,0.178549,0.055621
163,urbanLibrary_2,40.357259,-74.660325,40.360882,-74.664904,40.353636,-74.655746,0.178765,0.000000,0.000000,...,0.000000,0.438167,0.000000,0.132020,0.022914,0.000000,0.373323,0.024619,0.430181,0.016942
164,urbanLibrary_3,40.357259,-74.648996,40.360882,-74.653575,40.353636,-74.644417,0.012513,0.013579,0.000000,...,0.000018,0.334717,0.000000,0.048423,0.006504,0.000000,0.618944,0.002702,0.323427,0.000000
165,urbanLibrary_4,40.351510,-74.671573,40.355133,-74.676152,40.347887,-74.666994,0.000000,0.020661,0.000000,...,0.000000,0.078870,0.000000,0.038103,0.061693,0.008801,0.568359,0.039955,0.283089,0.000000
166,urbanLibrary_5,40.351510,-74.660325,40.355133,-74.664904,40.347887,-74.655746,0.099046,0.000000,0.000000,...,0.000000,0.834969,0.000000,0.065830,0.001245,0.002052,0.215779,0.009800,0.705294,0.000000
167,urbanLibrary_6,40.351510,-74.648996,40.355133,-74.653575,40.347887,-74.644417,0.031157,0.008836,0.000000,...,0.000000,0.485591,0.000000,0.070722,0.009648,0.003453,0.378842,0.011195,0.526140,0.000000
168,urbanLibrary_7,40.346620,-74.671573,40.350243,-74.676152,40.342997,-74.666994,0.000989,0.018350,0.020010,...,0.000000,0.132312,0.000000,0.053628,0.077581,0.006389,0.581186,0.005099,0.276117,0.000000
169,urbanLibrary_8,40.346620,-74.660325,40.350243,-74.664904,40.342997,-74.655746,0.002751,0.000000,0.008109,...,0.000000,0.942315,0.000000,0.128952,0.029165,0.006666,0.156421,0.003912,0.674884,0.000000
170,urbanLibrary_9,40.346620,-74.648996,40.350243,-74.653575,40.342997,-74.644417,0.222315,0.064744,0.006634,...,0.009602,0.571475,0.000000,0.157274,0.064795,0.025653,0.181737,0.097878,0.472663,0.000000

Now let's save this to CSV.

In [23]:
df2.to_csv("../satelliteData/landcover-nj-2023.csv", index = False)